# Generated by Django 2.2.16 on 2022-09-09 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_fallow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fallow',
            new_name='Follow',
        ),
    ]
